### ISSUE TITLE
README.md中，Key-Value的Key拼写错了。

### ISSUE THREAD

**Issue by xilou31** [YuQianhao/LightHttp#2]
![image](https://user-images.githubusercontent.com/44915143/104152016-675d1080-5419-11eb-9b16-251035dc1d6e.png)

**Comment by YuQianhao** [comment]
哈哈哈哈，抱歉，不做Android了，很久没看这个了

**Comment by xilou31** [comment]
过了一年才回issue哈哈，我也忘了这事了。
